import {FeatureCategory, FeatureItem} from './Feature'

export const digitalProjectFeatures: FeatureItem[] = [
  {
    id: 'feature-1',
    name: 'User Authentication',
    description: 'Login, registration, password reset, and profile management',
    workdays: 5,
    category: FeatureCategory.BACKEND,
    keywords: ['authentication', 'login', 'registration', 'user management'],
  },
  {
    id: 'feature-2',
    name: 'Real-Time Notifications',
    description: 'Email, push, and in-app notifications for user engagement',
    workdays: 4,
    category: FeatureCategory.BACKEND,
    keywords: ['notifications', 'real-time', 'user engagement'],
  },
  {
    id: 'feature-3',
    name: 'Payment Integration',
    description: 'Integration with payment gateways for secure transactions',
    workdays: 6,
    category: FeatureCategory.BACKEND,
    keywords: ['payment', 'integration', 'transactions'],
  },
  {
    id: 'feature-4',
    name: 'Geolocation Services',
    description: 'Location tracking and mapping functionalities',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['geolocation', 'mapping', 'location tracking'],
  },
  {
    id: 'feature-5',
    name: 'Search Functionality',
    description: 'Advanced search with filters and autocomplete',
    workdays: 5,
    category: FeatureCategory.FRONTEND,
    keywords: ['search', 'filters', 'autocomplete'],
  },
  {
    id: 'feature-6',
    name: 'Content Management System',
    description: 'Admin interface for managing content and media',
    workdays: 7,
    category: FeatureCategory.BACKEND,
    keywords: ['CMS', 'content management', 'admin interface'],
  },
  {
    id: 'feature-7',
    name: 'Automated Testing Suite',
    description: 'Unit, integration, and end-to-end tests for quality assurance',
    workdays: 6,
    category: FeatureCategory.QA,
    keywords: ['testing', 'automated', 'quality assurance'],
  },
  {
    id: 'feature-8',
    name: 'Continuous Integration/Deployment',
    description: 'CI/CD pipeline setup for automated builds and deployments',
    workdays: 5,
    category: FeatureCategory.DEVOPS,
    keywords: ['CI/CD', 'continuous integration', 'deployment'],
  },
  {
    id: 'feature-9',
    name: 'Multilingual Support',
    description: 'Localization and internationalization of the application',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['multilingual', 'localization', 'internationalization'],
  },
  {
    id: 'feature-10',
    name: 'Data Analytics Dashboard',
    description: 'Interactive dashboard displaying key metrics and analytics',
    workdays: 7,
    category: FeatureCategory.FRONTEND,
    keywords: ['analytics', 'dashboard', 'metrics'],
  },
  {
    id: 'feature-11',
    name: 'Offline Mode',
    description: 'Access and interact with content without an internet connection',
    workdays: 6,
    category: FeatureCategory.FRONTEND,
    keywords: ['offline', 'access', 'content'],
  },
  {
    id: 'feature-12',
    name: 'Social Media Integration',
    description: 'Connect and share content via social media platforms',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['social media', 'integration', 'sharing'],
  },
  {
    id: 'feature-13',
    name: 'Role-Based Access Control',
    description: 'Manage user permissions and access levels',
    workdays: 5,
    category: FeatureCategory.BACKEND,
    keywords: ['RBAC', 'access control', 'permissions'],
  },
  {
    id: 'feature-14',
    name: 'API Development',
    description: 'Design and implementation of RESTful or GraphQL APIs',
    workdays: 6,
    category: FeatureCategory.BACKEND,
    keywords: ['API', 'development', 'REST', 'GraphQL'],
  },
  {
    id: 'feature-15',
    name: 'Performance Optimization',
    description: 'Enhancements for faster load times and improved responsiveness',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['performance', 'optimization', 'load times'],
  },
  {
    id: 'feature-16',
    name: 'Secure Data Encryption',
    description: 'Implementation of data encryption for security',
    workdays: 5,
    category: FeatureCategory.BACKEND,
    keywords: ['encryption', 'data security', 'secure'],
  },
  {
    id: 'feature-17',
    name: 'Custom Reporting',
    description: 'Generation of tailored reports based on user data',
    workdays: 6,
    category: FeatureCategory.BACKEND,
    keywords: ['reporting', 'custom', 'data'],
  },
  {
    id: 'feature-18',
    name: 'Third-Party Integrations',
    description: 'Seamless integration with external services and APIs',
    workdays: 5,
    category: FeatureCategory.BACKEND,
    keywords: ['third-party', 'integration', 'services'],
  },
  {
    id: 'feature-19',
    name: 'User Feedback System',
    description: 'Collect and manage user feedback within the application',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['feedback', 'user', 'management'],
  },
  {
    id: 'feature-20',
    name: 'Scheduler and Calendar',
    description: 'Tools for scheduling events and managing calendars',
    workdays: 5,
    category: FeatureCategory.FRONTEND,
    keywords: ['scheduler', 'calendar', 'events'],
  },
  {
    id: 'feature-21',
    name: 'File Upload and Management',
    description: 'Upload, store, and manage files within the application',
    workdays: 4,
    category: FeatureCategory.BACKEND,
    keywords: ['file upload', 'management', 'storage'],
  },
  {
    id: 'feature-22',
    name: 'Chat and Messaging',
    description: 'Real-time communication between users',
    workdays: 6,
    category: FeatureCategory.FRONTEND,
    keywords: ['chat', 'messaging', 'communication'],
  },
  {
    id: 'feature-23',
    name: 'Subscription Management',
    description: 'Handle user subscriptions and recurring payments',
    workdays: 5,
    category: FeatureCategory.BACKEND,
    keywords: ['subscription', 'management', 'payments'],
  },
  {
    id: 'feature-24',
    name: 'Interactive Tutorials',
    description: 'Guided walkthroughs to onboard new users',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['tutorials', 'interactive', 'onboarding'],
  },
  {
    id: 'feature-25',
    name: 'Customizable User Profiles',
    description: 'Allow users to personalize their profiles',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['customizable', 'user profiles', 'personalization'],
  },
  {
    id: 'feature-26',
    name: 'E-commerce Functionality',
    description: 'Product listings, shopping cart, and checkout processes',
    workdays: 7,
    category: FeatureCategory.FRONTEND,
    keywords: ['e-commerce', 'shopping cart', 'checkout'],
  },
  {
    id: 'feature-27',
    name: 'Blog and News Module',
    description: 'Publish and manage articles and news updates',
    workdays: 5,
    category: FeatureCategory.BACKEND,
    keywords: ['blog', 'news', 'management'],
  },
  {
    id: 'feature-28',
    name: 'Event Management',
    description: 'Create, manage, and promote events',
    workdays: 6,
    category: FeatureCategory.BACKEND,
    keywords: ['event management', 'promotion', 'creation'],
  },
  {
    id: 'feature-29',
    name: 'Survey and Polls',
    description: 'Design and conduct surveys or polls',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['survey', 'polls', 'design'],
  },
  {
    id: 'feature-30',
    name: 'Help Center and FAQs',
    description: 'Provide users with help articles and a frequently asked questions section',
    workdays: 3,
    category: FeatureCategory.FRONTEND,
    keywords: ['help center', 'FAQs', 'support'],
  },
  {
    id: 'feature-31',
    name: 'In-App Rating System',
    description: 'Allow users to rate content, services, or products within the app',
    workdays: 3,
    category: FeatureCategory.FRONTEND,
    keywords: ['rating', 'in-app', 'user feedback'],
  },
  {
    id: 'feature-32',
    name: 'Session Management',
    description: 'Handle user sessions with login persistence and timeout rules',
    workdays: 4,
    category: FeatureCategory.BACKEND,
    keywords: ['session management', 'login', 'persistence'],
  },
  {
    id: 'feature-33',
    name: 'Splash Screen',
    description: 'Initial branding screen shown during app loading',
    workdays: 0.5,
    category: FeatureCategory.DESIGN,
    keywords: ['splash screen', 'branding', 'loading'],
  },
  {
    id: 'feature-34',
    name: 'Onboarding Tutorial',
    description: 'Introduction screens to guide first-time users',
    workdays: 2,
    category: FeatureCategory.FRONTEND,
    keywords: ['onboarding', 'tutorial', 'guidance'],
  },
  {
    id: 'feature-35',
    name: 'Transaction History',
    description: 'Display of past transactions with status and filtering',
    workdays: 3,
    category: FeatureCategory.BACKEND,
    keywords: ['transaction history', 'display', 'filtering'],
  },
  {
    id: 'feature-36',
    name: 'Address Book',
    description: 'User-managed delivery or billing addresses',
    workdays: 3,
    category: FeatureCategory.FRONTEND,
    keywords: ['address book', 'delivery', 'billing'],
  },
  {
    id: 'feature-37',
    name: 'Calendar Range Picker',
    description: 'Date range selection component integrated into forms or filters',
    workdays: 3,
    category: FeatureCategory.FRONTEND,
    keywords: ['calendar', 'range picker', 'date selection'],
  },
  {
    id: 'feature-38',
    name: 'User Subscription Plan',
    description: 'Customizable plans with periodic billing and feature access',
    workdays: 5,
    category: FeatureCategory.BACKEND,
    keywords: ['subscription plan', 'customizable', 'billing'],
  },
  {
    id: 'feature-39',
    name: 'Notification Center',
    description: 'In-app list of past and unread notifications',
    workdays: 3,
    category: FeatureCategory.FRONTEND,
    keywords: ['notification center', 'in-app', 'notifications'],
  },
  {
    id: 'feature-40',
    name: 'Admin Panel',
    description: 'Back-office interface to manage app data and users',
    workdays: 6,
    category: FeatureCategory.FRONTEND,
    keywords: ['admin panel', 'management', 'data'],
  },
  {
    id: 'feature-41',
    name: 'High-Fidelity Mockups',
    description: 'Detailed UI designs created before implementation',
    workdays: 4,
    category: FeatureCategory.DESIGN,
    keywords: ['mockups', 'UI design', 'fidelity'],
  },
  {
    id: 'feature-42',
    name: 'Database Schema Design',
    description: 'Creation of optimized and scalable database schemas',
    workdays: 4,
    category: FeatureCategory.DATABASE,
    keywords: ['database', 'schema design', 'optimization'],
  },
  {
    id: 'feature-43',
    name: 'Data Import and Export',
    description: 'Ability to import/export datasets in various formats',
    workdays: 3,
    category: FeatureCategory.BACKEND,
    keywords: ['data import', 'data export', 'datasets'],
  },
  {
    id: 'feature-44',
    name: 'Audit Logs',
    description: 'Track actions performed by users or systems over time',
    workdays: 3,
    category: FeatureCategory.BACKEND,
    keywords: ['audit logs', 'tracking', 'actions'],
  },
  {
    id: 'feature-45',
    name: 'User Consent Management',
    description: 'Manage and store user consent in compliance with privacy regulations',
    workdays: 3,
    category: FeatureCategory.BACKEND,
    keywords: ['user consent', 'management', 'privacy'],
  },
  {
    id: 'feature-46',
    name: 'A/B Testing System',
    description: 'Serve and evaluate different feature variants for testing',
    workdays: 2,
    category: FeatureCategory.BACKEND,
    keywords: ['A/B testing', 'evaluation', 'variants'],
  },
  {
    id: 'feature-47',
    name: 'Error Monitoring & Logging',
    description: 'Track and analyze application errors and exceptions',
    workdays: 3,
    category: FeatureCategory.DEVOPS,
    keywords: ['error monitoring', 'logging', 'analysis'],
  },
  {
    id: 'feature-48',
    name: 'App Store Optimization Metadata',
    description: 'Preparation of app store visuals and copywriting for SEO',
    workdays: 2,
    category: FeatureCategory.DESIGN,
    keywords: ['app store', 'optimization', 'metadata'],
  },
  {
    id: 'feature-49',
    name: 'A/B Testing System',
    description: 'Test different UI variations and track user behavior',
    workdays: 2,
    category: FeatureCategory.FRONTEND,
    keywords: ['A/B testing', 'user behavior', 'UI variations'],
  },
  {
    id: 'feature-50',
    name: 'Smart Recommendations',
    description: 'AI-powered content and product recommendations',
    workdays: 2,
    category: FeatureCategory.BACKEND,
    keywords: ['recommendations', 'AI', 'personalization'],
  },
  {
    id: 'feature-51',
    name: 'AI Chat Assistant',
    description: 'Intelligent chatbot for user support and interactions',
    workdays: 5,
    category: FeatureCategory.BACKEND,
    keywords: ['AI', 'chatbot', 'user support'],
  },
  {
    id: 'feature-52',
    name: 'LLM Integration',
    description:
      'Integration of a large language model (e.g. GPT) with prompt management and response handling',
    workdays: 4,
    category: FeatureCategory.BACKEND,
    keywords: ['LLM', 'GPT', 'prompt', 'language model'],
  },
  {
    id: 'feature-53',
    name: 'Prompt Engineering Interface',
    description: 'UI and logic to craft, debug, and version prompts sent to an LLM',
    workdays: 3,
    category: FeatureCategory.FRONTEND,
    keywords: ['prompt', 'LLM', 'interface', 'debugging'],
  },
  {
    id: 'feature-54',
    name: 'LLM Response Moderation',
    description: 'Safety layer to analyze, reject or redact risky AI-generated responses',
    workdays: 3,
    category: FeatureCategory.BACKEND,
    keywords: ['moderation', 'LLM', 'safety', 'filtering'],
  },
  {
    id: 'feature-55',
    name: 'Medical Record Viewer',
    description: 'Secure interface to access and display electronic medical records (EMR)',
    workdays: 4,
    category: FeatureCategory.FRONTEND,
    keywords: ['medical', 'EMR', 'records', 'health'],
  },
  {
    id: 'feature-56',
    name: 'Health Data Sync',
    description: 'Synchronization of health-related data from wearables or connected devices',
    workdays: 4,
    category: FeatureCategory.BACKEND,
    keywords: ['health', 'sync', 'data', 'devices'],
  },
  {
    id: 'feature-57',
    name: 'Bluetooth Device Pairing',
    description: 'Pairing flow and interface for Bluetooth-connected medical devices',
    workdays: 3,
    category: FeatureCategory.FRONTEND,
    keywords: ['bluetooth', 'device', 'medical', 'pairing'],
  },
  {
    id: 'feature-58',
    name: 'Bluetooth Data Streaming',
    description: 'Live data stream from Bluetooth medical devices to the application backend',
    workdays: 4,
    category: FeatureCategory.BACKEND,
    keywords: ['bluetooth', 'data', 'streaming', 'medical'],
  },
  {
    id: 'feature-59',
    name: 'Patient Consent Workflow',
    description: 'Digital consent forms and workflow management for medical data sharing',
    workdays: 3,
    category: FeatureCategory.BACKEND,
    keywords: ['patient', 'consent', 'workflow', 'medical'],
  },
  {
    id: 'feature-60',
    name: 'Anonymized Data Export',
    description: 'Export of anonymized medical data sets for research and compliance',
    workdays: 3,
    category: FeatureCategory.BACKEND,
    keywords: ['anonymized', 'export', 'data', 'research'],
  },
]
